#############################################################################
# Makefile for building: SQLQueryGenerator
# Generated by qmake (3.1) (Qt 5.12.3)
# Project:  SQLQueryGenerator.pro
# Template: app
# Command: /home/raidg/Qt/5.12.3/gcc_64/bin/qmake -o Makefile SQLQueryGenerator.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++1z -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/raidg/Qt/5.12.3/gcc_64/include -I/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets -I/home/raidg/Qt/5.12.3/gcc_64/include/QtGui -I/home/raidg/Qt/5.12.3/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I. -I/home/raidg/Qt/5.12.3/gcc_64/mkspecs/linux-clang
QMAKE         = /home/raidg/Qt/5.12.3/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/raidg/Qt/5.12.3/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/raidg/Qt/5.12.3/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SQLQueryGenerator1.0.0
DISTDIR = /mnt/D/Documents/Szkola_s4/CPP/Qt_Projects/SQLQueryGenerator/.tmp/SQLQueryGenerator1.0.0
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++ -Wl,-rpath,/home/raidg/Qt/5.12.3/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/raidg/Qt/5.12.3/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		sqlinterpreter.cpp moc_mainwindow.cpp \
		moc_sqlinterpreter.cpp
OBJECTS       = main.o \
		mainwindow.o \
		sqlinterpreter.o \
		moc_mainwindow.o \
		moc_sqlinterpreter.o
DIST          = /home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/spec_pre.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/unix.conf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/linux.conf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/sanitize.conf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base.conf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/clang.conf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/qconfig.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/qt_functions.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/qt_config.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/linux-clang/qmake.conf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/toolchain.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/default_pre.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/resolve_config.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/default_post.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/qml_debug.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/warn_on.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/qt.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/resources.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/moc.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/uic.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/unix/thread.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/qmake_use.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/file_copies.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/exceptions.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/yacc.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/lex.prf \
		SQLQueryGenerator.pro mainwindow.h \
		sqlinterpreter.h main.cpp \
		mainwindow.cpp \
		sqlinterpreter.cpp
QMAKE_TARGET  = SQLQueryGenerator
DESTDIR       = 
TARGET        = SQLQueryGenerator


first: all
####### Build rules

SQLQueryGenerator: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SQLQueryGenerator.pro /home/raidg/Qt/5.12.3/gcc_64/mkspecs/linux-clang/qmake.conf /home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/spec_pre.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/unix.conf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/linux.conf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/sanitize.conf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base.conf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/clang.conf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/qconfig.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/qt_functions.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/qt_config.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/linux-clang/qmake.conf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/toolchain.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/default_pre.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/resolve_config.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/default_post.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/qml_debug.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/warn_on.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/qt.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/resources.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/moc.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/uic.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/unix/thread.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/qmake_use.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/file_copies.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/exceptions.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/yacc.prf \
		/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/lex.prf \
		SQLQueryGenerator.pro \
		/home/raidg/Qt/5.12.3/gcc_64/lib/libQt5Widgets.prl \
		/home/raidg/Qt/5.12.3/gcc_64/lib/libQt5Gui.prl \
		/home/raidg/Qt/5.12.3/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile SQLQueryGenerator.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/spec_pre.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/unix.conf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/linux.conf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/sanitize.conf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base.conf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/common/clang.conf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/qconfig.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/qt_functions.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/qt_config.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/linux-clang/qmake.conf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/toolchain.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/default_pre.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/resolve_config.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/default_post.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/qml_debug.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/warn_on.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/qt.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/resources.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/moc.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/unix/opengl.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/uic.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/unix/thread.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/qmake_use.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/file_copies.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/testcase_targets.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/exceptions.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/yacc.prf:
/home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/lex.prf:
SQLQueryGenerator.pro:
/home/raidg/Qt/5.12.3/gcc_64/lib/libQt5Widgets.prl:
/home/raidg/Qt/5.12.3/gcc_64/lib/libQt5Gui.prl:
/home/raidg/Qt/5.12.3/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile SQLQueryGenerator.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile SQLQueryGenerator

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h sqlinterpreter.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp sqlinterpreter.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/data/dummy.cpp
	clang++ -pipe -g -std=gnu++1z -Wall -W -dM -E -o moc_predefs.h /home/raidg/Qt/5.12.3/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_sqlinterpreter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_sqlinterpreter.cpp
moc_mainwindow.cpp: mainwindow.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QMainWindow \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtguiglobal.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qconfig.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qtcore-config.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qlogging.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qflags.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmutex.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qnumeric.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qversiontagging.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtgui-config.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qwidget.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qwindowdefs.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qnamespace.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobject.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstring.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qchar.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qbytearray.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qrefcount.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qarraydata.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringliteral.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringview.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringbuilder.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qlist.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qalgorithms.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qiterator.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qhashfunctions.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qpair.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qbytearraylist.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringlist.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qregexp.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringmatcher.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcoreevent.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qscopedpointer.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmetatype.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobject_impl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmargins.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpaintdevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qrect.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsize.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qpoint.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpalette.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qcolor.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qrgb.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qrgba64.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qbrush.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qvector.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qmatrix.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpolygon.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qregion.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qdatastream.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qiodevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qline.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtransform.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpainterpath.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qimage.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpixelformat.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpixmap.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qshareddata.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qhash.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qfont.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qfontmetrics.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qfontinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qcursor.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qkeysequence.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qevent.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qvariant.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmap.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qdebug.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qtextstream.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qlocale.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qset.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qurl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qurlquery.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qfile.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qfiledevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qvector2d.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtouchdevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qicon.h \
		sqlinterpreter.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QTextEdit \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtextedit.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qframe.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextdocument.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextoption.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextcursor.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextformat.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpen.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QMessageBox \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qmessagebox.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qdialog.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/QMap \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/QDebug \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QFileDialog \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qfiledialog.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qdir.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qfileinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QListWidgetItem \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qlistwidget.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qlistview.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractitemview.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qabstractitemmodel.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qitemselectionmodel.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qstyleoption.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qvalidator.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qregularexpression.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qslider.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractslider.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qstyle.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtabbar.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qrubberband.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QSystemTrayIcon \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qsystemtrayicon.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/QDesktopServices \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qdesktopservices.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstandardpaths.h \
		moc_predefs.h \
		/home/raidg/Qt/5.12.3/gcc_64/bin/moc
	/home/raidg/Qt/5.12.3/gcc_64/bin/moc $(DEFINES) --include /mnt/D/Documents/Szkola_s4/CPP/Qt_Projects/SQLQueryGenerator/moc_predefs.h -I/home/raidg/Qt/5.12.3/gcc_64/mkspecs/linux-clang -I/mnt/D/Documents/Szkola_s4/CPP/Qt_Projects/SQLQueryGenerator -I/home/raidg/Qt/5.12.3/gcc_64/include -I/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets -I/home/raidg/Qt/5.12.3/gcc_64/include/QtGui -I/home/raidg/Qt/5.12.3/gcc_64/include/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/local/include -I/usr/lib/llvm-3.8/lib/clang/3.8.1/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_sqlinterpreter.cpp: sqlinterpreter.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QTextEdit \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtextedit.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtguiglobal.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qconfig.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qtcore-config.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qlogging.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qflags.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmutex.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qnumeric.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qversiontagging.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtgui-config.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qframe.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qwidget.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qwindowdefs.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qnamespace.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobject.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstring.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qchar.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qbytearray.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qrefcount.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qarraydata.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringliteral.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringview.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringbuilder.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qlist.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qalgorithms.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qiterator.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qhashfunctions.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qpair.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qbytearraylist.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringlist.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qregexp.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringmatcher.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcoreevent.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qscopedpointer.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmetatype.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobject_impl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmargins.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpaintdevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qrect.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsize.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qpoint.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpalette.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qcolor.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qrgb.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qrgba64.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qbrush.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qvector.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qmatrix.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpolygon.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qregion.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qdatastream.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qiodevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qline.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtransform.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpainterpath.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qimage.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpixelformat.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpixmap.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qshareddata.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qhash.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qfont.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qfontmetrics.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qfontinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qcursor.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qkeysequence.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qevent.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qvariant.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmap.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qdebug.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qtextstream.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qlocale.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qset.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qurl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qurlquery.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qfile.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qfiledevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qvector2d.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtouchdevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextdocument.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextoption.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextcursor.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextformat.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpen.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QMessageBox \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qmessagebox.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qdialog.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/QMap \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QMainWindow \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qicon.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/QDebug \
		moc_predefs.h \
		/home/raidg/Qt/5.12.3/gcc_64/bin/moc
	/home/raidg/Qt/5.12.3/gcc_64/bin/moc $(DEFINES) --include /mnt/D/Documents/Szkola_s4/CPP/Qt_Projects/SQLQueryGenerator/moc_predefs.h -I/home/raidg/Qt/5.12.3/gcc_64/mkspecs/linux-clang -I/mnt/D/Documents/Szkola_s4/CPP/Qt_Projects/SQLQueryGenerator -I/home/raidg/Qt/5.12.3/gcc_64/include -I/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets -I/home/raidg/Qt/5.12.3/gcc_64/include/QtGui -I/home/raidg/Qt/5.12.3/gcc_64/include/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/x86_64-linux-gnu/c++/6.3.0 -I/usr/include/c++/6.3.0/backward -I/usr/local/include -I/usr/lib/llvm-3.8/lib/clang/3.8.1/include -I/usr/include/x86_64-linux-gnu -I/usr/include sqlinterpreter.h -o moc_sqlinterpreter.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/home/raidg/Qt/5.12.3/gcc_64/bin/uic
	/home/raidg/Qt/5.12.3/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QMainWindow \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtguiglobal.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qconfig.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qtcore-config.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qlogging.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qflags.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmutex.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qnumeric.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qversiontagging.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtgui-config.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qwidget.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qwindowdefs.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qnamespace.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobject.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstring.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qchar.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qbytearray.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qrefcount.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qarraydata.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringliteral.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringview.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringbuilder.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qlist.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qalgorithms.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qiterator.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qhashfunctions.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qpair.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qbytearraylist.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringlist.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qregexp.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringmatcher.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcoreevent.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qscopedpointer.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmetatype.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobject_impl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmargins.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpaintdevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qrect.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsize.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qpoint.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpalette.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qcolor.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qrgb.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qrgba64.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qbrush.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qvector.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qmatrix.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpolygon.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qregion.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qdatastream.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qiodevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qline.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtransform.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpainterpath.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qimage.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpixelformat.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpixmap.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qshareddata.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qhash.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qfont.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qfontmetrics.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qfontinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qcursor.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qkeysequence.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qevent.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qvariant.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmap.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qdebug.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qtextstream.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qlocale.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qset.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qurl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qurlquery.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qfile.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qfiledevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qvector2d.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtouchdevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qicon.h \
		sqlinterpreter.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QTextEdit \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtextedit.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qframe.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextdocument.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextoption.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextcursor.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextformat.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpen.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QMessageBox \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qmessagebox.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qdialog.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/QMap \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/QDebug \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QFileDialog \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qfiledialog.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qdir.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qfileinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QListWidgetItem \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qlistwidget.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qlistview.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractitemview.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qabstractitemmodel.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qitemselectionmodel.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qstyleoption.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qvalidator.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qregularexpression.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qslider.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractslider.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qstyle.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtabbar.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qrubberband.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QSystemTrayIcon \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qsystemtrayicon.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/QDesktopServices \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qdesktopservices.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstandardpaths.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QApplication \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qapplication.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcoreapplication.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qeventloop.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qguiapplication.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp /home/raidg/Qt/5.12.3/gcc_64/include/QtCore/QDebug \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qdebug.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qalgorithms.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qconfig.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qtcore-config.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qlogging.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qflags.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmutex.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qnumeric.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qversiontagging.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qhash.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qchar.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qiterator.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qlist.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qrefcount.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qarraydata.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qhashfunctions.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstring.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qbytearray.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qnamespace.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringliteral.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringview.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringbuilder.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qpair.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qbytearraylist.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringlist.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qregexp.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringmatcher.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmap.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qtextstream.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qiodevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobject.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcoreevent.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qscopedpointer.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmetatype.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobject_impl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qlocale.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qvariant.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qshareddata.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qvector.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qpoint.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qset.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		mainwindow.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QMainWindow \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtguiglobal.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtgui-config.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qwidget.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qwindowdefs.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmargins.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpaintdevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qrect.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsize.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpalette.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qcolor.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qrgb.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qrgba64.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qbrush.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qmatrix.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpolygon.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qregion.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qdatastream.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qline.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtransform.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpainterpath.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qimage.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpixelformat.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpixmap.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qfont.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qfontmetrics.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qfontinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qcursor.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qkeysequence.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qevent.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qurl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qurlquery.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qfile.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qfiledevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qvector2d.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtouchdevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qicon.h \
		sqlinterpreter.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QTextEdit \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtextedit.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qframe.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextdocument.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextoption.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextcursor.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextformat.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpen.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QMessageBox \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qmessagebox.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qdialog.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/QMap \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QFileDialog \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qfiledialog.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qdir.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qfileinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QListWidgetItem \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qlistwidget.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qlistview.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractitemview.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qabstractitemmodel.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qitemselectionmodel.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qstyleoption.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qvalidator.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qregularexpression.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qslider.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractslider.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qstyle.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtabbar.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qrubberband.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QSystemTrayIcon \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qsystemtrayicon.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/QDesktopServices \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qdesktopservices.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstandardpaths.h \
		ui_mainwindow.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/QVariant \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QApplication \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qapplication.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcoreapplication.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qeventloop.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qguiapplication.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qinputmethod.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QHBoxLayout \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qboxlayout.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qlayout.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qgridlayout.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QLineEdit \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qlineedit.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QListWidget \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QPushButton \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qpushbutton.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

sqlinterpreter.o: sqlinterpreter.cpp sqlinterpreter.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QTextEdit \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtextedit.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtguiglobal.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qconfig.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qtcore-config.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qlogging.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qflags.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmutex.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qnumeric.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qversiontagging.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtgui-config.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qframe.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qwidget.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qwindowdefs.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qnamespace.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobject.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstring.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qchar.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qbytearray.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qrefcount.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qarraydata.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringliteral.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringview.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringbuilder.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qlist.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qalgorithms.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qiterator.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qhashfunctions.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qpair.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qbytearraylist.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringlist.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qregexp.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qstringmatcher.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcoreevent.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qscopedpointer.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmetatype.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qobject_impl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmargins.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpaintdevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qrect.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsize.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qpoint.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpalette.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qcolor.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qrgb.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qrgba64.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qbrush.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qvector.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qmatrix.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpolygon.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qregion.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qdatastream.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qiodevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qline.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtransform.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpainterpath.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qimage.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpixelformat.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpixmap.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qshareddata.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qhash.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qfont.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qfontmetrics.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qfontinfo.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qcursor.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qkeysequence.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qevent.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qvariant.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qmap.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qdebug.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qtextstream.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qlocale.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qset.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qurl.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qurlquery.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qfile.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/qfiledevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qvector2d.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtouchdevice.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextdocument.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextoption.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextcursor.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qtextformat.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qpen.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QMessageBox \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qmessagebox.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qdialog.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/QMap \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/QMainWindow \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtGui/qicon.h \
		/home/raidg/Qt/5.12.3/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sqlinterpreter.o sqlinterpreter.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_sqlinterpreter.o: moc_sqlinterpreter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sqlinterpreter.o moc_sqlinterpreter.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/SQLQueryGenerator/bin || mkdir -p $(INSTALL_ROOT)/opt/SQLQueryGenerator/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/SQLQueryGenerator/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/SQLQueryGenerator/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/SQLQueryGenerator/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

